osx:
  tags:
    - osx
  script:
    - source scripts/build_osx.sh
linux:
  tags:
    - linux
  script:
    - source scripts/build_linux.sh
windows:
  tags:
    - windows
  script:
    - cmd /C scripts\build_windows.cmd