build:
  script:
    - git submodule update --init
    - export WORKSPACE=$PWD
    - cd $AEON_LIBRARIES_PATH
    - git fetch --prune
    - git checkout origin/master
    - cd $WORKSPACE
    - export BUILD_DIR=ci_build
    - mkdir $BUILD_DIR
    - cd $BUILD_DIR
    - cmake -DCMAKE_INSTALL_PREFIX=install -DAEON_ENABLE_CLANG_COVERAGE=1 ../
    - cmake --build . --config Debug
    - ctest -C Debug --verbose
    - lcov --directory . --capture --output-file test.info
    - lcov --remove test.info '/Applications/Xcode.app/*' '*/Gitlab/osx_clang/*' '*/tests/test_*' --output-file test.info.clean
    - lcov --summary test.info
